Steppan
whos-gabi/insurance-blog-platform pull request #1
Opened 2024-11-18 20:31 UTC by StefanCondorache

1) Eu tarziu mi-am dat seama, dar daca trebuie schimb totul in limba engleza.
2) Comentariile pe care le consideri inutile le-am pus mai mult pentru mine sa inteleg ce face fiecare, ca prima data lucrez cu asta

2024-11-18 20:44 UTC, whos-gabi requested changes
Mai trebuie un commit sa repari astea, in rest **auth** pare normal, dar trebuie testat ulterior

2024-11-18 20:44 UTC, whos-gabi commented on routes/auth.js
> +router.post('/autentificare-admin', async (req, res) => {
Denumirea rutelor trebuie sa fie inrromana, ca si denumirile variabilelor

comentariile pot sa fie si in romana, dar sa te obistunesti sa le pui doar acolo unde este necesar, unde nu se intelege la prima vedere ce se intampla

2024-11-18 20:44 UTC, whos-gabi commented on routes/auth.js
> +            return res.status(400).json({ message : "Username sau parola incorecta"})
mesajele de eroare sau logurlie pot fi in romana

2024-11-18 20:44 UTC, whos-gabi commented on routes/auth.js
> +            const token = jwt.sign({ username }, "Secret_Key");
aici cheia de encriptare JTW trebuie sa o iei din .ENV

2024-11-18 20:44 UTC, whos-gabi commented on routes/auth.js
> +const DB_URL = process.env.DB_URL;
nu ai nevoie de db_url aici, nu?

2024-11-18 20:50 UTC, StefanCondorache commented on routes/auth.js
> +const DB_URL = process.env.DB_URL;
adica mai tarziu, cand o sa scriu functie de selectare din baza de date dupa username. Sau nu trebuie?

2024-11-18 21:07 UTC, whos-gabi commented on routes/auth.js
> +const DB_URL = process.env.DB_URL;
stiind ca dashboardul are un admin, nu cred ca este nevoie sa il pastram in BD, se poate in **.env**, dar sa fie encrypted
https://emn178.github.io/online-tools/sha256.html

2024-11-19 21:59 UTC, whos-gabi commented
# Round Up
- bad code
- needs refactoring

2024-11-19 21:59 UTC, closed without merging